### ISSUE TITLE
[index.html] - add a button at the bottom to jump to the top of the page

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/HackerNews#19]
```js
function scrollToTop() {
    $('.btn-scroll-top').on('click', function() {
        document.body.scrollTop = 0; // For Safari
        document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    });
    
    const scrollBtn = $('.btn-scroll-top');
    
    $(window).on('scroll', function() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            $(scrollBtn).removeClass('d-none');
        } else {
            $(scrollBtn).addClass('d-none');
        }
    });
}
```

**Comment by rrickgauer** [comment]
Put the button near the top of the html page:

```html
<button type="button" class="btn btn-sm btn-light btn-scroll-top d-none">Back to top</button>
```

**Comment by rrickgauer** [comment]
```css
.btn-scroll-top {
    position: fixed;
    bottom: 20px;
    right: 30px;
    z-index: 99;
}
```
