### ISSUE TITLE
Find a cool google font for the h1 at the top

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/HackerNews#3]
find some google fonts

**Comment by rrickgauer** [comment]
HTML

```html
<link href="https://fonts.googleapis.com/css?family=Archivo:500|Open+Sans:300,700" rel="stylesheet">
```

CSS

```css
body {
 font-family: 'Open Sans', sans-serif;
 font-weight: 300;
}

h1, h2, h3, h4, h5, h6 {
 font-family: 'Archivo', sans-serif;
 font-weight: 500;
}
```
